[workspace]

members = [
    "apps/cloud",
    "apps/keck",
    "libs/cang-jie",
    "libs/jwst",
    "libs/jwst-ffi",
    "libs/jwst-jni",
    "libs/jwst-logger",
    "libs/jwst-py",
    "libs/jwst-storage",
    "libs/jwst-wasm",
    "libs/y-sync",
    "libs/yrs",
]

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
