name: Build Jwst

on:
    workflow_dispatch:
    push:
        branches: [master]
        paths:
            - 'apps/keck/**'
            - '.github/deployment/Dockerfile-jwst'
            - '.github/deployment/Dockerfile-jwst-prod'
            - '.github/workflows/jwst.yml'
    pull_request:
        branches: [master]
        paths:
            - 'apps/keck/**'
            - '.github/deployment/Dockerfile-jwst'
            - '.github/deployment/Dockerfile-jwst-prod'
            - '.github/workflows/jwst.yml'

# Cancels all previous workflow runs for pull requests that have not completed.
# See https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
    # The concurrency group contains the workflow name and the branch name for
    # pull requests or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

env:
    REGISTRY: ghcr.io
    NAMESPACE: toeverything
    JWST_IMAGE_NAME: jwst
    IMAGE_TAG: canary-${{ github.sha }}
    IMAGE_TAG_LATEST: nightly-latest
    LOCAL_CACHE: localhost:5000/toeverything/relocate:latest

jobs:
    jwst:
        runs-on: self-hosted
        environment: development
        permissions:
            contents: read
            packages: write

        services:
            registry:
                image: registry:2
                ports:
                    - 5000:5000

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Log in to the Container registry
              uses: docker/login-action@v2
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.ACTIONS_PACKAGE_PUBLISH }}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v1
              with:
                  driver-opts: network=host

            - name: Extract metadata (tags, labels) for Docker (jwst)
              id: meta_jwst
              uses: docker/metadata-action@v4
              with:
                  images: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.JWST_IMAGE_NAME }}
                  tags: ${{ env.IMAGE_TAG_LATEST }}

            - name: Build and push Docker image (jwst-baseline)
              uses: docker/build-push-action@v3
              with:
                  context: .
                  push: true
                  file: ./.github/deployment/Dockerfile-jwst
                  tags: ${{ env.LOCAL_CACHE }}
                  target: jwst

            - name: Build and push Docker image (jwst)
              uses: docker/build-push-action@v3
              with:
                  context: .
                  platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
                  file: ./.github/deployment/Dockerfile-jwst-prod
                  push: ${{ github.ref == 'refs/heads/master' && true || false }}
                  tags: ${{ steps.meta_jwst.outputs.tags }}
                  labels: ${{ steps.meta_jwst.outputs.labels }}
                  target: jwst
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: nightly
                  override: true
            - uses: actions-rs/cargo@v1
              with:
                  command: test
                  args: --workspace --exclude yrs --all-features --no-fail-fast
              env:
                  CARGO_INCREMENTAL: '0'
                  RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
                  RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
            - id: coverage
              uses: actions-rs/grcov@v0.1
            - uses: codecov/codecov-action@v3
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  files: ${{ steps.coverage.outputs.report }}
                  flags: unittests
                  name: jwst
                  fail_ci_if_error: true
                  verbose: true
