name: Build Jwst

on:
    workflow_dispatch:
    push:
        branches: [master]
        paths:
            - 'apps/keck/**'
            - '.github/deployment/Dockerfile-jwst'
            - '.github/workflows/jwst.yml'
    pull_request:
        branches: [master]
        paths:
            - 'apps/keck/**'
            - '.github/deployment/Dockerfile-jwst'
            - '.github/workflows/jwst.yml'

# Cancels all previous workflow runs for pull requests that have not completed.
# See https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
    # The concurrency group contains the workflow name and the branch name for
    # pull requests or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

env:
    REGISTRY: ghcr.io
    NAMESPACE: toeverything
    JWST_IMAGE_NAME: jwst
    IMAGE_TAG: canary-${{ github.sha }}
    IMAGE_TAG_LATEST: nightly-latest

jobs:
    jwst:
        runs-on: ubuntu-latest
        environment: development
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Log in to the Container registry
              uses: docker/login-action@v2
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.ACTIONS_PACKAGE_PUBLISH }}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v1

            - name: Extract metadata (tags, labels) for Docker (jwst)
              id: meta_jwst
              uses: docker/metadata-action@v4
              with:
                  images: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.JWST_IMAGE_NAME }}
                  tags: |
                      ${{ env.IMAGE_TAG }}
                      ${{ env.IMAGE_TAG_LATEST }}

            - name: Build and push Docker image (jwst-amd64)
              uses: docker/build-push-action@v3
              with:
                  context: .
                  platforms: linux/amd64
                  file: ./.github/deployment/Dockerfile-jwst-amd64
                  push: ${{ github.ref == 'refs/heads/master' && true || false }}
                  tags: ${{ steps.meta_jwst.outputs.tags }}
                  labels: ${{ steps.meta_jwst.outputs.labels }}
                  target: jwst

            - name: Build and push Docker image (jwst-aarch64)
              uses: docker/build-push-action@v3
              with:
                  context: .
                  platforms: linux/arm64/v8
                  file: ./.github/deployment/Dockerfile-jwst-amd64
                  push: ${{ github.ref == 'refs/heads/master' && true || false }}
                  tags: ${{ steps.meta_jwst.outputs.tags }}
                  labels: ${{ steps.meta_jwst.outputs.labels }}
                  target: jwst
