name: Build Keck

on:
    workflow_dispatch:
    push:
        branches: [master]
        paths:
            - 'apps/keck/**'
            - 'libs/**'
            - '.github/deployment/Dockerfile-keck'
            - '.github/workflows/keck.yml'
    pull_request:
        branches: [master]
        paths:
            - 'apps/keck/**'
            - 'libs/**'
            - '.github/deployment/Dockerfile-keck'
            - '.github/workflows/keck.yml'

# Cancels all previous workflow runs for pull requests that have not completed.
# See https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
    # The concurrency group contains the workflow name and the branch name for
    # pull requests or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

env:
    REGISTRY: ghcr.io
    NAMESPACE: toeverything
    KECK_IMAGE_NAME: keck_rust
    IMAGE_TAG: canary-${{ github.sha }}
    IMAGE_TAG_LATEST: nightly-latest

jobs:
    keck:
        runs-on: ubuntu-latest
        environment: development
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Log in to the Container registry
              uses: docker/login-action@v2
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.ACTIONS_PACKAGE_PUBLISH }}

            - name: Extract metadata (tags, labels) for Docker (keck)
              id: meta_keck
              uses: docker/metadata-action@v4
              with:
                  images: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.KECK_IMAGE_NAME }}
                  tags: |
                      ${{ env.IMAGE_TAG }}
                      ${{ env.IMAGE_TAG_LATEST }}

            - name: Build and push Docker image (keck)
              uses: docker/build-push-action@v3
              with:
                  context: .
                  file: ./.github/deployment/Dockerfile-keck
                  push: ${{ github.ref == 'refs/heads/master' && true || false }}
                  tags: ${{ steps.meta_keck.outputs.tags }}
                  labels: ${{ steps.meta_keck.outputs.labels }}
                  target: keck
